import type { PublicSource } from "@fonteia/domain";

export const SOURCE_CATALOG: PublicSource[] = [
  {
    id: "receita-leiloes-sle",
    name: "Receita Federal - Sistema de Leilao Eletronico",
    owner: "Receita Federal do Brasil",
    sourceUrl: "https://www25.receita.fazenda.gov.br/sle-sociedade/portal/editais-disponiveis",
    docsUrl: "https://www.gov.br/receitafederal/pt-br/assuntos/leilao",
    status: "fragile_operational",
    accessKind: "open",
    reliability: "official_fragile",
    modules: ["leiloes"],
    refreshCadence: "daily",
    commercialRisk: "medium",
    notes: "Portal publico oficial. Nao ha API publica documentada; tratar endpoints operacionais como frageis e usar cache/fallback.",
  },
  {
    id: "pncp-consulta",
    name: "Portal Nacional de Contratacoes Publicas - API de Consulta",
    owner: "Governo Federal",
    sourceUrl: "https://pncp.gov.br/api/consulta/swagger-ui/index.html",
    docsUrl: "https://www.gov.br/pncp/pt-br/acesso-a-informacao/dados-abertos",
    status: "connected",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["licitacoes", "empresas", "municipios"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "API oficial para consultas de contratacoes, atas, contratos e planos de contratacao.",
  },
  {
    id: "compras-gov-dados-abertos",
    name: "Compras.gov.br - Dados Abertos",
    owner: "Ministerio da Gestao e da Inovacao em Servicos Publicos",
    sourceUrl: "https://dadosabertos.compras.gov.br/",
    docsUrl: "https://www.gov.br/compras/pt-br/acesso-a-informacao/manuais/manual-dados-abertos/manual-api-compras.pdf",
    status: "connected",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["licitacoes", "empresas", "municipios"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Dados de compras federais, fornecedores, itens, precos praticados e contratos.",
  },
  {
    id: "portal-transparencia-api",
    name: "Portal da Transparencia - API de Dados",
    owner: "Controladoria-Geral da Uniao",
    sourceUrl: "https://portaldatransparencia.gov.br/api-de-dados",
    docsUrl: "https://api.portaldatransparencia.gov.br/",
    status: "integrating",
    accessKind: "open_with_token",
    reliability: "official_stable",
    modules: ["empresas", "politica", "municipios", "licitacoes"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Exige token por cadastro. Fonte forte para despesas, contratos, sancoes, beneficios e servidores.",
  },
  {
    id: "camara-dados-abertos",
    name: "Camara dos Deputados - Dados Abertos",
    owner: "Camara dos Deputados",
    sourceUrl: "https://dadosabertos.camara.leg.br/",
    docsUrl: "https://dadosabertos.camara.leg.br/swagger/api.html",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["politica", "juridico"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Deputados, proposicoes, votacoes, comissoes, eventos e despesas parlamentares.",
  },
  {
    id: "senado-dados-abertos",
    name: "Senado Federal - Dados Abertos",
    owner: "Senado Federal",
    sourceUrl: "https://legis.senado.leg.br/dadosabertos/api-docs/swagger-ui/index.html",
    docsUrl: "https://www12.senado.leg.br/dados-abertos",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["politica", "juridico"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Materias, tramitacao, autores, comissoes e normas do Senado/Congresso.",
  },
  {
    id: "tse-dados-abertos",
    name: "TSE - Dados Abertos Eleitorais",
    owner: "Tribunal Superior Eleitoral",
    sourceUrl: "https://dadosabertos.tse.jus.br/",
    docsUrl: "https://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais-1",
    status: "open_no_api",
    accessKind: "public_files",
    reliability: "official_stable",
    modules: ["politica", "municipios"],
    refreshCadence: "manual",
    commercialRisk: "low",
    notes: "Dados eleitorais e repositorios oficiais. Muitos conjuntos sao arquivos, nao API transacional.",
  },
  {
    id: "cnj-datajud",
    name: "CNJ DataJud - API Publica",
    owner: "Conselho Nacional de Justica",
    sourceUrl: "https://www.cnj.jus.br/sistemas/datajud/api-publica/",
    docsUrl: "https://www.cnj.jus.br/sistemas/datajud/api-publica/",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["juridico", "empresas"],
    refreshCadence: "daily",
    commercialRisk: "medium",
    notes: "Metadados de processos judiciais. Requer cuidado com LGPD, escopo e expectativas de completude.",
  },
  {
    id: "inpi-dados-abertos",
    name: "INPI - Dados Abertos",
    owner: "Instituto Nacional da Propriedade Industrial",
    sourceUrl: "https://www.gov.br/inpi/pt-br/acesso-a-informacao/dados-abertos",
    docsUrl: "https://www.gov.br/inpi/pt-br/projetos-estrategicos/portal-de-servicos",
    status: "integrating",
    accessKind: "public_files",
    reliability: "official_fragile",
    modules: ["inpi", "empresas"],
    refreshCadence: "manual",
    commercialRisk: "medium",
    notes: "Dados abertos de marcas, patentes e outros servicos. Nova plataforma promete APIs JSON/XML ST.96.",
  },
  {
    id: "ibama-dados-abertos",
    name: "IBAMA - Dados Abertos",
    owner: "Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renovaveis",
    sourceUrl: "https://dadosabertos.ibama.gov.br/",
    docsUrl: "https://dadosabertos.ibama.gov.br/",
    status: "integrating",
    accessKind: "public_files",
    reliability: "official_stable",
    modules: ["ambiental", "empresas"],
    refreshCadence: "monthly",
    commercialRisk: "low",
    notes: "Bases ambientais, incluindo embargos e autos. Formatos variam por conjunto.",
  },
  {
    id: "inpe-terrabrasilis",
    name: "INPE TerraBrasilis",
    owner: "Instituto Nacional de Pesquisas Espaciais",
    sourceUrl: "https://terrabrasilis.dpi.inpe.br/",
    docsUrl: "https://terrabrasilis.dpi.inpe.br/",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["ambiental", "municipios"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "PRODES, DETER e dados geoespaciais de monitoramento ambiental.",
  },
  {
    id: "inpe-queimadas",
    name: "INPE Queimadas - Dados Abertos",
    owner: "Instituto Nacional de Pesquisas Espaciais",
    sourceUrl: "https://data.inpe.br/queimadas/dados-abertos/",
    docsUrl: "https://data.inpe.br/queimadas/dados-abertos/",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["ambiental", "municipios"],
    refreshCadence: "hourly",
    commercialRisk: "low",
    notes: "Focos de fogo, risco de fogo e produtos geoespaciais.",
  },
  {
    id: "mapbiomas-alerta",
    name: "MapBiomas Alerta",
    owner: "MapBiomas",
    sourceUrl: "https://plataforma.alerta.mapbiomas.org/",
    docsUrl: "https://plataforma.alerta.mapbiomas.org/api",
    status: "complementary_non_government",
    accessKind: "open",
    reliability: "complementary",
    modules: ["ambiental"],
    refreshCadence: "daily",
    commercialRisk: "medium",
    notes: "Fonte complementar nao governamental, forte para alertas ambientais e validacao cruzada.",
  },
  {
    id: "ana-hidrowebservice",
    name: "ANA HidroWebservice",
    owner: "Agencia Nacional de Aguas e Saneamento Basico",
    sourceUrl: "https://www.ana.gov.br/hidrowebservice/swagger-ui/index.html",
    docsUrl: "https://www.ana.gov.br/hidrowebservice/swagger-ui/index.html",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["ambiental", "municipios"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Dados hidrologicos oficiais para risco hidrico, clima e territorio.",
  },
  {
    id: "tesouro-siconfi",
    name: "Tesouro Nacional - Siconfi API",
    owner: "Tesouro Nacional",
    sourceUrl: "https://www.tesourotransparente.gov.br/consultas/consultas-siconfi/siconfi-api-de-dados-abertos",
    docsUrl: "https://apidatalake.tesouro.gov.br/docs/siconfi/",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["municipios", "politica"],
    refreshCadence: "monthly",
    commercialRisk: "low",
    notes: "Dados contabeis e fiscais de estados e municipios.",
  },
  {
    id: "transferegov-dados-abertos",
    name: "Transferegov.br - Dados Abertos",
    owner: "Governo Federal",
    sourceUrl: "https://www.gov.br/rededeparcerias/pt-br/acesso-informacao/dados-abertos",
    docsUrl: "https://www.gov.br/transferegov/pt-br/ferramentas-gestao/dados-abertos",
    status: "integrating",
    accessKind: "open",
    reliability: "official_stable",
    modules: ["municipios", "politica", "licitacoes"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "Transferencias, convenios, TEDs, obras e execucao de recursos publicos.",
  },
  {
    id: "bndes-dados-abertos",
    name: "BNDES - Dados Abertos",
    owner: "Banco Nacional de Desenvolvimento Economico e Social",
    sourceUrl: "https://dadosabertos.bndes.gov.br/",
    docsUrl: "https://dadosabertos.bndes.gov.br/",
    status: "open_no_api",
    accessKind: "public_files",
    reliability: "official_stable",
    modules: ["empresas", "politica", "municipios"],
    refreshCadence: "monthly",
    commercialRisk: "low",
    notes: "Financiamentos, desembolsos e informacoes publicas do BNDES.",
  },
  {
    id: "dou-inlabs",
    name: "Diario Oficial da Uniao - INLABS",
    owner: "Imprensa Nacional",
    sourceUrl: "https://inlabs.in.gov.br/",
    docsUrl: "https://inlabs.in.gov.br/",
    status: "integrating",
    accessKind: "open_with_token",
    reliability: "official_stable",
    modules: ["juridico", "politica", "licitacoes", "empresas"],
    refreshCadence: "daily",
    commercialRisk: "low",
    notes: "XML e PDF do DOU. Exige cadastro/login; XML nao substitui versao certificada oficial.",
  },
];

